---
title: "About posit::conf(2023)"
---

posit::conf(2023) is an annual conference organized by [Posit](https://posit.co/) (formerly RStudio). This event is all about bringing together the community and celebrating open-source data science. You can attend the conference either in person or virtually from September 17 to September 20!

The virtual experience of our hybrid conference is a unique experience that brings together R and Python enthusiasts from different countries, industries, and backgrounds to meet, chat, and share in the excitement of posit::conf online. 

The virtual experience includes:

* Livestreams of [over 100 keynote and talks](https://posit.co/blog/keynotes-and-talks-at-posit-conf-2023/) led by renowned speakers in data from September 19-20.
* On-demand recordings available shortly after the scheduled run time of keynotes and talks
* Question and answer sessions alongside other attendees during the talks
* The opportunity to chat, share, and learn with other attendees, no matter where they are, through our virtual networking platform. 
* Ask Me Anythings (AMAs) and demos from Posit developers, engineers, and community members.

If you are interested in registering to attend in person, please visit our [conference website](https://posit.co/conference/). [Workshops](https://pos.it/conf-workshops) are filling up fast, so get your seat today!

Follow us the conversation and share the excitement using the hashtag #positconf2023!