---
title: "How to host a virtual watch party"
---

Hosting a virtual watch party is a great way to bring your user group members together and enjoy an event like posit::conf(2023). Here are some simple steps to help you host a successful virtual watch party:

1. **Choose a location.** Ensure that you have a location with stable internet connection, a large screen, and a quiet environment. Test the virtual event portal recordings and make sure you are familiar with its features.
2. **Set a date and time:** Decide on a specific date and time for your watch party. Because our live streams will be available on demand shortly after the session, you have two options for scheduling an event:
    *  **Live:** Schedule a virtual watch party during posit::conf(2023). The live streams will take place from 9am - 6pm, Central Time/US. [See what time that is for you](https://www.timeanddate.com/time/difference/usa/chicago).
    * **Later date:** Schedule a virtual watch party after posit::conf(2023) hours. We hope to have recordings of sessions available on the virtual event portal within a few business days. This gives you the opportunity to schedule outside of the conf hours.
3. **Invite participants:** Send out invitations to your user group providing details about the watch party. Include the date, time, and the location.
4. **Share the conference stream:** On the day of the watch party, log in to the posit::conf virtual event portal. Share your screen with the participants, displaying the conference stream so everyone can watch and listen together.
5. **Encourage interaction:** During the talks, encourage participants to actively engage. Use the Q/A feature of the virtual event portal to ask questions alongside other attendees.
6. **Share on social media:** Share your virtual watch party fun on social media! We'd love to see photos, reflections on the talks, and discussion on the awesome tools mentioned during conf. Tag us using the hashtag #positconf2023 so we can reshare with our network, too!
7. **Networking:** Provide casual networking among participants during and after the streams.
8. **Follow up and share resources:** After the watch party, send a follow-up email to all participants. Express your appreciation for their attendance and provide any relevant resources discussed during the conference.

Please adhere to the code of conduct set by Posit.

We hope that you have a great virtual watch party experience!